CREATE TABLE usuarios (
    id MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
    nome VARCHAR(60) NOT NULL,
    email VARCHAR(80) NOT NULL,
    user VARCHAR(16) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
